# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Recipe.destroy_all
Ingredient.destroy_all

bob = User.create(email: 'bob@gmail.com', password: 'password')
rec1 = bob.recipes.create({name: "Quinoa Salad", cooktime: 30, img_url: 'http://images.media-allrecipes.com/userphotos/250x250/1081167.jpg'})
rec2 = bob.recipes.create({name: "Lemon Chicken Pasta", cooktime: 20, img_url: 'https://lh3.googleusercontent.com/cDmkWJ8P2xSPvXwwid4zr4p-I9pZWyeTFRIQu6zbG5SpF3Ao_TMulTOclXTAt9sze9SOZrGtJ_wSjmnj5okkNdFaFFqm=s535-c'})
rec3 = bob.recipes.create({name: "Salmon Nicoise", cooktime: 20, img_url: 'http://1.bp.blogspot.com/-LMkcFC6spW0/ThoMmKyehsI/AAAAAAAAAvc/CUc4nV-Hu40/s1600/IMG_9857.JPG'})
rec4 = bob.recipes.create({name: "Ceviche", cooktime: 45, img_url: 'http://www.simplyrecipes.com/wp-content/uploads/2008/07/shrimp-ceviche-method-2-600x400.jpg'})
rec5 = bob.recipes.create({name: "Bleu Burger", cooktime: 30, img_url: 'http://assets.kraftfoods.com/recipe_images/opendeploy/61863_640x428.jpg'})

ing1 = Ingredient.create({name: 'Quinoa' })
ing2 = Ingredient.create({name: 'Red Pepper' })
ing3 = Ingredient.create({name: 'Cherry Tomato' })
ing4 = Ingredient.create({name: 'Cucumber' })
ing5 = Ingredient.create({name: 'Green Pepper' })
ing6 = Ingredient.create({name: 'Olive Oil' })
ing7 = Ingredient.create({name: 'Onion' })
ing8 = Ingredient.create({name: 'Parsley' })
ing9 = Ingredient.create({name: 'Chicken Breast' })
ing10 = Ingredient.create({name: 'Penne Pasta' })
ing11 = Ingredient.create({name: 'Asparagus' })
ing12 = Ingredient.create({name: 'Parmesan' })
ing13 = Ingredient.create({name: 'Salmon Filet' })
ing14 = Ingredient.create({name: 'Romaine Lettuce' })
ing15 = Ingredient.create({name: 'Hard Boiled Egg' })
ing16 = Ingredient.create({name: 'Olives' })
ing17 = Ingredient.create({name: 'Shrimp' })
ing18 = Ingredient.create({name: 'Scallop' })
ing19 = Ingredient.create({name: 'Lime Juice' })
ing20 = Ingredient.create({name: 'Avocado' })
ing21 = Ingredient.create({name: 'Ground Beef' })
ing22 = Ingredient.create({name: 'Bleu Cheese' })
ing23 = Ingredient.create({name: 'Hamburger Bun' })
ing24 = Ingredient.create({name: 'Iceberg Lettuce' })
ing25 = Ingredient.create({name: 'Pickle' })


List.create({recipe: rec1, ingredient: ing1})
List.create({recipe: rec1, ingredient: ing2})
List.create({recipe: rec1, ingredient: ing3})
List.create({recipe: rec1, ingredient: ing4})
List.create({recipe: rec2, ingredient: ing9})
List.create({recipe: rec2, ingredient: ing10})
List.create({recipe: rec2, ingredient: ing11})
List.create({recipe: rec2, ingredient: ing12})
List.create({recipe: rec3, ingredient: ing13})
List.create({recipe: rec3, ingredient: ing14})
List.create({recipe: rec3, ingredient: ing15})
List.create({recipe: rec3, ingredient: ing16})
List.create({recipe: rec3, ingredient: ing11})
List.create({recipe: rec4, ingredient: ing17})
List.create({recipe: rec4, ingredient: ing18})
List.create({recipe: rec4, ingredient: ing19})
List.create({recipe: rec4, ingredient: ing20})
List.create({recipe: rec5, ingredient: ing21})
List.create({recipe: rec5, ingredient: ing22})
List.create({recipe: rec5, ingredient: ing23})
List.create({recipe: rec5, ingredient: ing24})
List.create({recipe: rec5, ingredient: ing25})
